### ISSUE TITLE
Synthesis.Bethesda.Execution.CliUnsuccessfulRunException: Error running solution patcher

### ISSUE THREAD

**Issue by khirasier** [SteveTownsend/AllGUDMeshGen#33]
[798.7][AllGUDMeshGen] System.ArgumentException: BOD2 type not expected on versions < 43
[798.7][AllGUDMeshGen]    at Mutagen.Bethesda.Skyrim.Internals.BodyTemplateBinaryOverlay.CustomFactory(OverlayStream stream, BinaryOverlayFactoryPackage package)
[798.7][AllGUDMeshGen]    at Mutagen.Bethesda.Skyrim.Internals.ArmorBinaryOverlay.GetBodyTemplateCustom()
[798.7][AllGUDMeshGen]    at Mutagen.Bethesda.Skyrim.Internals.ArmorBinaryOverlay.get_BodyTemplate()
[798.7][AllGUDMeshGen]    at AllGUD.MeshHandler.CollateShields() in C:\Users\khira\AppData\Local\Temp\Synthesis\f92452f7-427c-43fd-a8b0-42f90bf74ca6\Git\a0f4innb.2c3\Runner\AllGUDMeshGen\MeshHandler.cs:line 228
[798.7][AllGUDMeshGen]    at AllGUD.MeshHandler.Analyze() in C:\Users\khira\AppData\Local\Temp\Synthesis\f92452f7-427c-43fd-a8b0-42f90bf74ca6\Git\a0f4innb.2c3\Runner\AllGUDMeshGen\MeshHandler.cs:line 686
[798.7][AllGUDMeshGen]    at AllGUD.ScriptLess.RunPatch(IPatcherState`2 state) in C:\Users\khira\AppData\Local\Temp\Synthesis\f92452f7-427c-43fd-a8b0-42f90bf74ca6\Git\a0f4innb.2c3\Runner\AllGUDMeshGen\Program.cs:line 65
[798.7][AllGUDMeshGen]    at Mutagen.Bethesda.Synthesis.SynthesisPipeline.<>c__DisplayClass12_0`2.<<AddPatch>b__0>d.MoveNext() in D:\a\Synthesis\Synthesis\Mutagen.Bethesda.Synthesis\SynthesisPipeline.cs:line 93
[798.7][AllGUDMeshGen] --- End of stack trace from previous location ---
[798.7][AllGUDMeshGen]    at Mutagen.Bethesda.Synthesis.SynthesisPipeline.Run(RunSynthesisMutagenPatcher args, ModKey exportKey) in D:\a\Synthesis\Synthesis\Mutagen.Bethesda.Synthesis\SynthesisPipeline.cs:line 455
[798.7][AllGUDMeshGen]    at Mutagen.Bethesda.Synthesis.SynthesisPipeline.Run(RunSynthesisMutagenPatcher args) in D:\a\Synthesis\Synthesis\Mutagen.Bethesda.Synthesis\SynthesisPipeline.cs:line 403
[798.7][AllGUDMeshGen]    at Mutagen.Bethesda.Synthesis.SynthesisPipeline.<>c__DisplayClass36_0.<<InternalRun>b__1>d.MoveNext() in D:\a\Synthesis\Synthesis\Mutagen.Bethesda.Synthesis\SynthesisPipeline.cs:line 377
[798.8][AllGUDMeshGen] Model 00284C:Dawnguard.esm/DLC01\Armor\Auriel\aurielsshield.nif with type Shield added
[798.8][AllGUDMeshGen] Model 026610:Skyrim.esm/Armor\Spellbreaker\Spellbreaker.nif with type Shield added
[798.8][AllGUDMeshGen] Model 2AD08C:Tools of Kagrenac.esp/Armor\Elven\ElvenShield.nif with type Shield added
[798.8][AllGUDMeshGen] Model 0214F3:Skyrim.esm/Armor\StormCloaks\shield.nif with type Shield added
[798.8][AllGUDMeshGen] ARMA 0214F3:Skyrim.esm has alternate textures in Male Model
[798.8][AllGUDMeshGen] ARMA 0214F3:Skyrim.esm has alternate textures in Male Model
[798.8][AllGUDMeshGen] ARMA 0214F3:Skyrim.esm has alternate textures in Male Model
[798.8][AllGUDMeshGen] ARMA 0214F3:Skyrim.esm has alternate textures in Male Model
[798.8][AllGUDMeshGen] ARMA 0214F3:Skyrim.esm has alternate textures in Male Model
[798.8][AllGUDMeshGen] Model 048DD7:Skyrim.esm/Armor\Glass\GlassShield.nif with type Shield added
[798.8][AllGUDMeshGen] Model 036881:Skyrim.esm/Armor\Dragonscale\DragonscaleShield.nif with type Shield added
[798.8][AllGUDMeshGen] Model 0E400D:Skyrim.esm/Weapons\Ebony\EbonyShield.nif with type Shield added
[798.8][AllGUDMeshGen] Model 021339:Skyrim.esm/Armor\Dragonbone\DragonboneShield.nif with type Shield added
[798.8][AllGUDMeshGen] Model 0AFB81:Skyrim.esm/Armor\Daedric\1stPersonDaedricShield.nif with type Shield added
[798.8][AllGUDMeshGen] Model 013EB6:Dawnguard.esm/DLC01\Armor\Dwarven\1stPersonDwarvenShieldCrystal.nif with type Shield added
[798.8][AllGUDMeshGen] Model 03A276:Dragonborn.esm/DLC02\Armor\StalhrimShield\stalhrimshield.nif with type Shield added
[798.8][AllGUDMeshGen] Model 05C866:MLU.esp/Armor\nobleartifacts\Eleidon\eleidon.nif with type Shield added
[798.8][AllGUDMeshGen] Model 00085A:DCR_KingCrusaderMegaPack_SSE.esp/weapons\DarkCrusaderReforged\BladeSetReloaded\DefenderShield\DefenderIIShield.nif with type Shield added
[798.8][AllGUDMeshGen] Model 017B12:TrueHel.esp/Armor\Iron\Shield.nif with type Shield added
[798.8][AllGUDMeshGen] Model 104DD1:Skyrim.esm/Weapons\SpikedShield\SpikedShield.nif with type Shield added
[798.8][AllGUDMeshGen] Model 02983C:WheelsOfLull.esp/Lull\Armor\lull_shield.nif with type Shield added
[798.8][AllGUDMeshGen] Model 16627E:LegacyoftheDragonborn.esm/armor\Shields\VikingSn\VikingSn.nif with type Shield added
[798.8][AllGUDMeshGen] Model 16627D:LegacyoftheDragonborn.esm/armor\Shields\Aged Round Shield\AgedRoundShield.nif with type Shield added
[798.8][AllGUDMeshGen] Model 00435F:The Ultimate Zerofrost Armor Collection.esp/armor\Valkyrie Armor\HeimdallShield\HeimdallShield0.nif with type Shield added
[798.8][AllGUDMeshGen] Model 0064DC:The Ultimate Zerofrost Armor Collection.esp/armor\Valkyrie Armor\HeimdallShield\HeimdallShield.nif with type Shield added
[798.8][AllGUDMeshGen] Model 0ADCA0:Judgment Wenches.esp/dlc01\armor\dawnguard\1stpersondwarvenshieldaetherium.nif with type Shield added
[798.8][AllGUDMeshGen] Model 26A803:Darkend.esp/armor\steel\heatershield.nif with type Shield added
[798.8][AllGUDMeshGen] Model 38A3BD:Darkend.esp/armor\OldKnightShield\OldKnightShield.nif with type Shield added
[798.8][AllGUDMeshGen] Model 38CC14:Darkend.esp/armor\Orc Cresent Shield\OrcCresent.nif with type Shield added
[798.8][AllGUDMeshGen] Model 38CC16:Darkend.esp/armor\Shield of the Crusader Rusted\SOTCR.nif with type Shield added
[798.8][AllGUDMeshGen] Model 013A43:The Amazing World of Bikini Armors REMASTERED.esp/armor\shitty\elven\shield.nif with type Shield added
[798.8][AllGUDMeshGen] Model 2690F0:Hateful Wenches.esp/armor\Bullwark of Azzinoth\Bulwark.nif with type Shield added
[798.8][AllGUDMeshGen] Error while running
Synthesis.Bethesda.Execution.CliUnsuccessfulRunException: Error running solution patcher
   at Synthesis.Bethesda.Execution.Patchers.SolutionPatcherRun.Run(RunSynthesisPatcher settings, CancellationToken cancel)
   at Synthesis.Bethesda.Execution.Runner.Run[TKey](String workingDirectory, ModPath outputPath, String dataFolder, IEnumerable`1 loadOrder, GameRelease release, IEnumerable`1 patchers, IRunReporter`1 reporter, CancellationToken cancellation, ModPath sourcePath, PersistenceMode persistenceMode, String persistencePath)
[798.8] Finished patcher run.

**Comment by technicallyJack** [comment]
As the log says, it's because you have a mod (or several most likely, from my own experience) that is Form 43. My guess is Hateful Wenches.esp since it's the last one listed. Converting to 44 might break the mod so it's up to you if you want to take the risk and convert it. You can also ask the mod creator if they know how to do so and can update it. If you use Mod Organizer 2, you can see a list of your Form 43 mods in the top right corner. Your other option, apart from converting it, is to disable any Form 43 mods you have when you run the AllGUD Patcher.
![image](https://user-images.githubusercontent.com/25068959/133530684-bff419c9-f862-4ec4-9377-d735395eaae3.png)

**Comment by SteveTownsend** [comment]
Yes this is a Synthesis data check, not direct output from this patcher.
