### ISSUE TITLE
Various Node errors

### ISSUE THREAD

**Issue by BrentW89** [SteveTownsend/AllGUDMeshGen#38]
What's wrong and how do we fix this?

Compiling
No extra data to consider
("C:\Users\sales\AppData\Local\Temp\Synthesis\dede4e0e-aed9-42b8-91d6-8636a160a44c\Git\tvczenlh.okj\Runner\AllGUDMeshGen"): "dotnet" "build \"AllGUDMeshGen.csproj\" --runtime win-x64 -c Release"
Compiled
Sha "a92cdabf3d4785f6003986b9486bd6566202ccd1"
Running
(""): "dotnet" "run --project \"C:\Users\sales\AppData\Local\Temp\Synthesis\dede4e0e-aed9-42b8-91d6-8636a160a44c\Git\tvczenlh.okj\Runner\AllGUDMeshGen\AllGUDMeshGen.csproj\" --runtime win-x64 -c Release --no-build run-patcher --DataFolderPath \"C:\Program Files (x86)\Steam\steamapps\common\SkyrimVR\Data\" --ExtraDataFolder \"C:\Users\sales\Documents\Synthesis\Data\Skyrim VR\AllGUDMeshGen\" --GameRelease SkyrimVR --ModKey Synthesis.esp --LoadOrderFilePath C:\Users\sales\AppData\Local\Temp\Synthesis\dede4e0e-aed9-42b8-91d6-8636a160a44c\Workspace\Synthesis\Plugins.txt --LoadOrderIncludesCreationClub --OutputPath \"C:\Users\sales\AppData\Local\Temp\Synthesis\dede4e0e-aed9-42b8-91d6-8636a160a44c\Workspace\Synthesis\1 - AllGUDMeshGen\Synthesis.esp\" --PatcherName AllGUDMeshGen --PersistencePath C:\Users\sales\AppData\Local\Temp\Synthesis\dede4e0e-aed9-42b8-91d6-8636a160a44c\Persistence"
Mutagen version: 0.34.1
Mutagen sha: fdba08aed6d046d9b998345d0df21cacf90cb97f
Synthesis version: 0.21.4
Synthesis sha: a1e9d0f7b4f087f424af382760b1e40f895da84b
run-patcher --DataFolderPath "C:\Program Files (x86)\Steam\steamapps\common\SkyrimVR\Data" --ExtraDataFolder "C:\Users\sales\Documents\Synthesis\Data\Skyrim VR\AllGUDMeshGen" --GameRelease SkyrimVR --ModKey Synthesis.esp --LoadOrderFilePath C:\Users\sales\AppData\Local\Temp\Synthesis\dede4e0e-aed9-42b8-91d6-8636a160a44c\Workspace\Synthesis\Plugins.txt --LoadOrderIncludesCreationClub --OutputPath "C:\Users\sales\AppData\Local\Temp\Synthesis\dede4e0e-aed9-42b8-91d6-8636a160a44c\Workspace\Synthesis\1 - AllGUDMeshGen\Synthesis.esp" --PatcherName AllGUDMeshGen --PersistencePath C:\Users\sales\AppData\Local\Temp\Synthesis\dede4e0e-aed9-42b8-91d6-8636a160a44c\Persistence
Prepping state.
Language: English
Using TextFileSharedFormKeyAllocator allocator
Can use localization: True
Localized: False
Running patch.
Reading settings: C:\Users\sales\Documents\Synthesis\Data\Skyrim VR\AllGUDMeshGen\settings.json
Process meshes relative to C:/Users/sales/AppData/Roaming/Vortex/skyrimvr/mods/
Skeleton Mesh C:/Users/sales/AppData/Roaming/Vortex/skyrimvr/mods/Odin - Summons Redone-46516-1-2-1632887998\Meshes\1Clannfear\skeleton.nif
This skeleton is missing one or more required Nodes 
This Skeleton needs required AllGUD Armour Node WeaponSwordArmor
This Skeleton needs required AllGUD Armour Node WeaponDaggerArmor
This Skeleton needs required AllGUD Armour Node WeaponAxeArmor
This Skeleton needs required AllGUD Armour Node WeaponMaceArmor
This Skeleton needs required AllGUD Armour Node WeaponBackArmor
This Skeleton needs required AllGUD Armour Node WeaponBowArmor
This Skeleton is confirmed to be Human
Patched Weapon at Node 46/WeaponDaggerArmor as 283/WeaponDaggerArmor with parent 13
Patched Weapon at Node 47/WeaponAxeArmor as 284/WeaponAxeArmor with parent 13
Patched Weapon at Node 48/WeaponSwordArmor as 285/WeaponSwordArmor with parent 13
Patched Weapon at Node 49/WeaponMaceArmor as 286/WeaponMaceArmor with parent 13
Patched Weapon at Node 240/WeaponBackArmor as 287/WeaponBackArmor with parent 109
Patched Weapon at Node 241/WeaponBowArmor as 288/WeaponBowArmor with parent 109
All Weapon nodes patched for Skeleton, saving to C:/Users/sales/AppData/Roaming/Vortex/skyrimvr/mods/All GUD Synthesis Output/meshes/actors/character/Odin - Summons Redone-46516-1-2-1632887998\Meshes\1Clannfear\skeleton.nif
Skeleton Mesh C:/Users/sales/AppData/Roaming/Vortex/skyrimvr/mods/SMIM SE 2-07-659-2-07\meshes\loadscreenart\loadscreenskeleton.nif
This skeleton is missing one or more required Nodes 
This Skeleton needs required AllGUD Armour Node WeaponSwordArmor
This Skeleton needs required AllGUD Armour Node WeaponDaggerArmor
This Skeleton needs required AllGUD Armour Node WeaponAxeArmor
This Skeleton needs required AllGUD Armour Node WeaponMaceArmor
This Skeleton needs required AllGUD Armour Node WeaponBackArmor
This Skeleton needs required AllGUD Armour Node WeaponBowArmor
Skeleton Mesh C:/Users/sales/AppData/Roaming/Vortex/skyrimvr/mods/Song of the Green 1.3-11278-1-3-1630437169\Meshes\018Auri\yakkuruskeleton.nif
This skeleton is missing one or more required Nodes 
This Skeleton needs required AllGUD Armour Node WeaponSwordArmor
This Skeleton needs required AllGUD Armour Node WeaponDaggerArmor
This Skeleton needs required AllGUD Armour Node WeaponAxeArmor
This Skeleton needs required AllGUD Armour Node WeaponMaceArmor
This Skeleton needs required AllGUD Armour Node WeaponBackArmor
This Skeleton needs required AllGUD Armour Node WeaponBowArmor
Skeleton Mesh C:/Users/sales/AppData/Roaming/Vortex/skyrimvr/mods/XP32 Maximum Skeleton Special Extended-1988-4-80-1610196777\meshes\Slim Horse Race\skeleton_slimhorse.nif
This skeleton is missing one or more required Nodes 
This Skeleton needs required AllGUD Armour Node WeaponSwordArmor
This Skeleton needs required AllGUD Armour Node WeaponDaggerArmor
This Skeleton needs required AllGUD Armour Node WeaponAxeArmor
This Skeleton needs required AllGUD Armour Node WeaponMaceArmor
This Skeleton needs required AllGUD Armour Node WeaponBackArmor
This Skeleton needs required AllGUD Armour Node WeaponBowArmor
Skeleton Mesh C:/Users/sales/AppData/Roaming/Vortex/skyrimvr/mods/XP32 Maximum Skeleton Special Extended-1988-4-80-1610196777\meshes\War Horse\whskeleton.nif
This skeleton is missing one or more required Nodes 
This Skeleton needs required AllGUD Armour Node WeaponSwordArmor
This Skeleton needs required AllGUD Armour Node WeaponDaggerArmor
This Skeleton needs required AllGUD Armour Node WeaponAxeArmor
This Skeleton needs required AllGUD Armour Node WeaponMaceArmor
This Skeleton needs required AllGUD Armour Node WeaponBackArmor
This Skeleton needs required AllGUD Armour Node WeaponBowArmor
Skeleton Mesh C:/Users/sales/AppData/Roaming/Vortex/skyrimvr/mods/Carved Brink Pillars Edition-24351-Beta-1554388716\Meshes\HPGoblands\Actors\HPGThanosSkeleton.nif
This skeleton is missing one or more required Nodes 
This Skeleton needs required AllGUD Armour Node WeaponSwordArmor
This Skeleton needs required AllGUD Armour Node WeaponDaggerArmor
This Skeleton needs required AllGUD Armour Node WeaponAxeArmor
This Skeleton needs required AllGUD Armour Node WeaponMaceArmor
This Skeleton needs required AllGUD Armour Node WeaponBackArmor
This Skeleton needs required AllGUD Armour Node WeaponBowArmor
This Skeleton is confirmed to be Human
Patched Weapon at Node 47/WeaponDaggerArmor as 331/WeaponDaggerArmor with parent 14
Patched Weapon at Node 48/WeaponAxeArmor as 332/WeaponAxeArmor with parent 14
Patched Weapon at Node 49/WeaponSwordArmor as 333/WeaponSwordArmor with parent 14
Patched Weapon at Node 50/WeaponMaceArmor as 334/WeaponMaceArmor with parent 14
System.InvalidCastException: Unable to cast object of type 'nifly.BSTriShape' to type 'nifly.NiNode'.
   at AllGUD.SkeletonHandler.PatchWeaponNodes(NifFile nif, NiNode node, UInt32 parentId, ISet`1 weapons) in C:\Users\sales\AppData\Local\Temp\Synthesis\dede4e0e-aed9-42b8-91d6-8636a160a44c\Git\tvczenlh.okj\Runner\AllGUDMeshGen\SkeletonHandler.cs:line 80
   at AllGUD.SkeletonHandler.PatchWeaponNodes(NifFile nif, NiNode node, UInt32 parentId, ISet`1 weapons) in C:\Users\sales\AppData\Local\Temp\Synthesis\dede4e0e-aed9-42b8-91d6-8636a160a44c\Git\tvczenlh.okj\Runner\AllGUDMeshGen\SkeletonHandler.cs:line 80
   at AllGUD.SkeletonHandler.PatchWeaponNodes(NifFile nif, NiNode node, UInt32 parentId, ISet`1 weapons) in C:\Users\sales\AppData\Local\Temp\Synthesis\dede4e0e-aed9-42b8-91d6-8636a160a44c\Git\tvczenlh.okj\Runner\AllGUDMeshGen\SkeletonHandler.cs:line 80
   at AllGUD.SkeletonHandler.PatchWeaponNodes(NifFile nif, NiNode node, UInt32 parentId, ISet`1 weapons) in C:\Users\sales\AppData\Local\Temp\Synthesis\dede4e0e-aed9-42b8-91d6-8636a160a44c\Git\tvczenlh.okj\Runner\AllGUDMeshGen\SkeletonHandler.cs:line 80
   at AllGUD.SkeletonHandler.PatchSkeleton(String nifName) in C:\Users\sales\AppData\Local\Temp\Synthesis\dede4e0e-aed9-42b8-91d6-8636a160a44c\Git\tvczenlh.okj\Runner\AllGUDMeshGen\SkeletonHandler.cs:line 179
   at AllGUD.SkeletonHandler.PatchIfHuman() in C:\Users\sales\AppData\Local\Temp\Synthesis\dede4e0e-aed9-42b8-91d6-8636a160a44c\Git\tvczenlh.okj\Runner\AllGUDMeshGen\SkeletonHandler.cs:line 211
   at AllGUD.ScriptLess.RunPatch(IPatcherState`2 state) in C:\Users\sales\AppData\Local\Temp\Synthesis\dede4e0e-aed9-42b8-91d6-8636a160a44c\Git\tvczenlh.okj\Runner\AllGUDMeshGen\Program.cs:line 60
   at Mutagen.Bethesda.Synthesis.SynthesisPipeline.<>c__DisplayClass12_0`2.<<AddPatch>b__0>d.MoveNext() in D:\a\Synthesis\Synthesis\Mutagen.Bethesda.Synthesis\SynthesisPipeline.cs:line 103
--- End of stack trace from previous location ---
   at Mutagen.Bethesda.Synthesis.SynthesisPipeline.Run(RunSynthesisMutagenPatcher args, Nullable`1 exportKey, IFileSystem fileSystem) in D:\a\Synthesis\Synthesis\Mutagen.Bethesda.Synthesis\SynthesisPipeline.cs:line 555
   at Mutagen.Bethesda.Synthesis.SynthesisPipeline.Run(RunSynthesisMutagenPatcher args, IFileSystem fileSystem) in D:\a\Synthesis\Synthesis\Mutagen.Bethesda.Synthesis\SynthesisPipeline.cs:line 453
   at Mutagen.Bethesda.Synthesis.SynthesisPipeline.<>c__DisplayClass36_0.<<InternalRun>b__1>d.MoveNext() in D:\a\Synthesis\Synthesis\Mutagen.Bethesda.Synthesis\SynthesisPipeline.cs:line 416
Synthesis.Bethesda.Execution.CliUnsuccessfulRunException: Error running solution patcher
   at Synthesis.Bethesda.Execution.Patchers.Running.Solution.SolutionPatcherRunner.Run(RunSynthesisPatcher settings, CancellationToken cancel) in D:\a\Synthesis\Synthesis\Synthesis.Bethesda.Execution\Patchers\Running\Solution\SolutionPatcherRunner.cs:line 55
   at Synthesis.Bethesda.Execution.Patchers.Running.Solution.SolutionPatcherRun.Run(RunSynthesisPatcher settings, CancellationToken cancel) in D:\a\Synthesis\Synthesis\Synthesis.Bethesda.Execution\Patchers\Running\Solution\SolutionPatcherRun.cs:line 57
   at Synthesis.Bethesda.Execution.Running.Runner.RunAPatcher.Run(IGroupRun groupRun, PatcherPrepBundle prepBundle, CancellationToken cancellation, Nullable`1 sourcePath, RunParameters runParameters) in D:\a\Synthesis\Synthesis\Synthesis.Bethesda.Execution\Running\Runner\RunAPatcher.cs:line 70

**Comment by SteveTownsend** [comment]
The failing mesh is literally the only thing added by Carved Brink Pillars Edition. I run Carved Brink ESM and I don't see this error.

**Comment by SteveTownsend** [comment]
By the way, you could also blacklist this mesh but that's the same as uninstalling the entire Pillars Edition

**Comment by BrentW89** [comment]
I don't see how uninstalling that Pillars Edition patch is going to fix this issue when the log file indicates issues with NIF files from all sorts of mods including AllGUI, XP32, Odin, etc. Can you please take a closer look at the error log?

**Comment by SteveTownsend** [comment]
> the log file indicates issues with NIF files from all sorts of mods

No, it indicates workflow information about many mods and a failure on exactly one:
```
Skeleton Mesh C:/Users/sales/AppData/Roaming/Vortex/skyrimvr/mods/Carved Brink Pillars Edition-24351-Beta-1554388716\Meshes\HPGoblands\Actors\HPGThanosSkeleton.nif
This skeleton is missing one or more required Nodes
This Skeleton needs required AllGUD Armour Node WeaponSwordArmor
This Skeleton needs required AllGUD Armour Node WeaponDaggerArmor
This Skeleton needs required AllGUD Armour Node WeaponAxeArmor
This Skeleton needs required AllGUD Armour Node WeaponMaceArmor
This Skeleton needs required AllGUD Armour Node WeaponBackArmor
This Skeleton needs required AllGUD Armour Node WeaponBowArmor
This Skeleton is confirmed to be Human
Patched Weapon at Node 47/WeaponDaggerArmor as 331/WeaponDaggerArmor with parent 14
Patched Weapon at Node 48/WeaponAxeArmor as 332/WeaponAxeArmor with parent 14
Patched Weapon at Node 49/WeaponSwordArmor as 333/WeaponSwordArmor with parent 14
Patched Weapon at Node 50/WeaponMaceArmor as 334/WeaponMaceArmor with parent 14
System.InvalidCastException: Unable to cast object of type 'nifly.BSTriShape' to type 'nifly.NiNode'.

```
