### ISSUE TITLE
Unknown Error occurring

### ISSUE THREAD

**Issue by BrentW89** [SteveTownsend/AllGUDMeshGen#39]
This patcher worked last week or so but now I'm getting the following error. I've tried Profile, Latest, Match, and Last Successful settings and deleted the module and re-added it to Synthesis, but still errors. All Geared up Derivative.esp is enabled. I want to say a longer log was generated when it errored the first time today but I didn't copy it, then I tried different version settings and the error seemed shorter. That's when I deleted and re-added it to no avail. My output paths seem correct and as they were, though I noticed a reference to "D:\a\Synthesis\Synthesis\Mutagen.Bethesda.Synthesis\SynthesisPipeline.cs" when I have no D: drive.  The carved brink patch you had me remove last time I hit an error is still removed, so not sure what's up.

Compiling
No extra data to consider
("C:\Users\sales\AppData\Local\Temp\Synthesis\dede4e0e-aed9-42b8-91d6-8636a160a44c\Git\btyw3aen.qik\Runner\AllGUDMeshGen"): "dotnet" "build \"AllGUDMeshGen.csproj\" --runtime win-x64 -c Release"
Compiled
Sha "a92cdabf3d4785f6003986b9486bd6566202ccd1"
Running
(""): "dotnet" "run --project \"C:\Users\sales\AppData\Local\Temp\Synthesis\dede4e0e-aed9-42b8-91d6-8636a160a44c\Git\btyw3aen.qik\Runner\AllGUDMeshGen\AllGUDMeshGen.csproj\" --runtime win-x64 -c Release --no-build run-patcher --DataFolderPath \"C:\Program Files (x86)\Steam\steamapps\common\SkyrimVR\Data\" --ExtraDataFolder \"C:\Users\sales\Documents\Synthesis\Data\Skyrim VR\AllGUDMeshGen\" --GameRelease SkyrimVR --ModKey Synthesis.esp --LoadOrderFilePath C:\Users\sales\AppData\Local\Temp\Synthesis\dede4e0e-aed9-42b8-91d6-8636a160a44c\Workspace\Synthesis\Plugins.txt --LoadOrderIncludesCreationClub --OutputPath \"C:\Users\sales\AppData\Local\Temp\Synthesis\dede4e0e-aed9-42b8-91d6-8636a160a44c\Workspace\Synthesis\1 - AllGUDMeshGen\Synthesis.esp\" --PatcherName AllGUDMeshGen --PersistencePath C:\Users\sales\AppData\Local\Temp\Synthesis\dede4e0e-aed9-42b8-91d6-8636a160a44c\Persistence"
Mutagen version: 0.35.1
Mutagen sha: d42ce7d96b44a8f362d07109e462101a1bc0438e
Synthesis version: 0.21.4
Synthesis sha: a1e9d0f7b4f087f424af382760b1e40f895da84b
run-patcher --DataFolderPath "C:\Program Files (x86)\Steam\steamapps\common\SkyrimVR\Data" --ExtraDataFolder "C:\Users\sales\Documents\Synthesis\Data\Skyrim VR\AllGUDMeshGen" --GameRelease SkyrimVR --ModKey Synthesis.esp --LoadOrderFilePath C:\Users\sales\AppData\Local\Temp\Synthesis\dede4e0e-aed9-42b8-91d6-8636a160a44c\Workspace\Synthesis\Plugins.txt --LoadOrderIncludesCreationClub --OutputPath "C:\Users\sales\AppData\Local\Temp\Synthesis\dede4e0e-aed9-42b8-91d6-8636a160a44c\Workspace\Synthesis\1 - AllGUDMeshGen\Synthesis.esp" --PatcherName AllGUDMeshGen --PersistencePath C:\Users\sales\AppData\Local\Temp\Synthesis\dede4e0e-aed9-42b8-91d6-8636a160a44c\Persistence
Prepping state.
Language: English
Using TextFileSharedFormKeyAllocator allocator
Can use localization: True
Localized: False
Running patch.
Reading settings: C:\Users\sales\Documents\Synthesis\Data\Skyrim VR\AllGUDMeshGen\settings.json
Settings Errors: 1
System.ArgumentException: Invalid Output File: reusing name of an existing directory: c:/Users/sales/AppData/Roaming/Vortex/skyrimvr/mods/All GUD Synthesis Output
   at AllGUD.Helper.EnsureOutputFileIsValid(String file) in C:\Users\sales\AppData\Local\Temp\Synthesis\dede4e0e-aed9-42b8-91d6-8636a160a44c\Git\btyw3aen.qik\Runner\AllGUDMeshGen\Settings\Helper.cs:line 65
   at AllGUD.Diagnostics.GetConfigErrors() in C:\Users\sales\AppData\Local\Temp\Synthesis\dede4e0e-aed9-42b8-91d6-8636a160a44c\Git\btyw3aen.qik\Runner\AllGUDMeshGen\Settings\Diagnostics.cs:line 43
System.ArgumentException: Bad Settings: AllGUD Patcher cannot run. Check diagnostic output and fix problems.
   at AllGUD.ScriptLess.RunPatch(IPatcherState`2 state) in C:\Users\sales\AppData\Local\Temp\Synthesis\dede4e0e-aed9-42b8-91d6-8636a160a44c\Git\btyw3aen.qik\Runner\AllGUDMeshGen\Program.cs:line 53
   at Mutagen.Bethesda.Synthesis.SynthesisPipeline.<>c__DisplayClass12_0`2.<<AddPatch>b__0>d.MoveNext() in D:\a\Synthesis\Synthesis\Mutagen.Bethesda.Synthesis\SynthesisPipeline.cs:line 103
--- End of stack trace from previous location ---
   at Mutagen.Bethesda.Synthesis.SynthesisPipeline.Run(RunSynthesisMutagenPatcher args, Nullable`1 exportKey, IFileSystem fileSystem) in D:\a\Synthesis\Synthesis\Mutagen.Bethesda.Synthesis\SynthesisPipeline.cs:line 555
   at Mutagen.Bethesda.Synthesis.SynthesisPipeline.Run(RunSynthesisMutagenPatcher args, IFileSystem fileSystem) in D:\a\Synthesis\Synthesis\Mutagen.Bethesda.Synthesis\SynthesisPipeline.cs:line 453
   at Mutagen.Bethesda.Synthesis.SynthesisPipeline.<>c__DisplayClass36_0.<<InternalRun>b__1>d.MoveNext() in D:\a\Synthesis\Synthesis\Mutagen.Bethesda.Synthesis\SynthesisPipeline.cs:line 416
Synthesis.Bethesda.Execution.CliUnsuccessfulRunException: Error running solution patcher
   at Synthesis.Bethesda.Execution.Patchers.Running.Solution.SolutionPatcherRunner.Run(RunSynthesisPatcher settings, CancellationToken cancel) in D:\a\Synthesis\Synthesis\Synthesis.Bethesda.Execution\Patchers\Running\Solution\SolutionPatcherRunner.cs:line 55
   at Synthesis.Bethesda.Execution.Patchers.Running.Solution.SolutionPatcherRun.Run(RunSynthesisPatcher settings, CancellationToken cancel) in D:\a\Synthesis\Synthesis\Synthesis.Bethesda.Execution\Patchers\Running\Solution\SolutionPatcherRun.cs:line 57
   at Synthesis.Bethesda.Execution.Running.Runner.RunAPatcher.Run(IGroupRun groupRun, PatcherPrepBundle prepBundle, CancellationToken cancellation, Nullable`1 sourcePath, RunParameters runParameters) in D:\a\Synthesis\Synthesis\Synthesis.Bethesda.Execution\Running\Runner\RunAPatcher.cs:line 70

![allgui-error2](https://user-images.githubusercontent.com/38072698/153048133-d8183565-34c9-4a9c-bf22-ae882f7e8666.jpg)

**Comment by mosharky** [comment]
The error has to do with your output folder. Specifically, `reusing name of an existing directory`. Not sure why that would give an error though
