### ISSUE TITLE
Cancellation token, Error running solution patcher

### ISSUE THREAD

**Issue by Atoro10** [SteveTownsend/AllGUDMeshGen#40]
I have this report every time i try and run the allGUDMeshGen
[Report.txt](https://github.com/SteveTownsend/AllGUDMeshGen/files/8602082/Report.txt)

**Comment by SteveTownsend** [comment]
in the file I see this. 

> System.ArgumentException: Invalid Output File: reusing name of an existing directory: C:/Users/Markus/AppData/Local/ModOrganizer/Skyrim Special Edition/mods/AllGUD Meshes
   at AllGUD.Helper.EnsureOutputFileIsValid(String file) in C:\Users\Markus\AppData\Local\Temp\Synthesis\wcxdbrvf.n5z\Git\jcqmoyqa.yxx\Runner\AllGUDMeshGen\Settings\Helper.cs:line 65
   at AllGUD.Diagnostics.GetConfigErrors() in C:\Users\Markus\AppData\Local\Temp\Synthesis\wcxdbrvf.n5z\Git\jcqmoyqa.yxx\Runner\AllGUDMeshGen\Settings\Diagnostics.cs:line 43
Item Positioner cannot use  as both Input and Output Folder

Apparently your config does not specify output location for Item Positioner. Usually this is the same output dir as all the others.

**Comment by Atoro10** [comment]
I added the output file to item positioning and still got the same erro
[Report 2.txt](https://github.com/SteveTownsend/AllGUDMeshGen/files/8602746/Report.2.txt)
r
