### ISSUE TITLE
Settings Errors

### ISSUE THREAD

**Issue by klimurk** [SteveTownsend/AllGUDMeshGen#43]
Hello. Can you please help me with this error. Thank you

`
Settings Errors: 2
Skeleton Patcher cannot use  as both Input and Output Folder
Item Positioner cannot use  as both Input and Output Folder
System.ArgumentException: Bad Settings: AllGUD Patcher cannot run. Check diagnostic output and fix problems.
   at AllGUD.ScriptLess.RunPatch(IPatcherState2 state) in C:\Users\klimurk\AppData\Local\Temp\Synthesis\kgknuxaq.koc\Git\ucrrtd0l.4dk\Runner\AllGUDMeshGen\Program.cs:line 53
   at Mutagen.Bethesda.Synthesis.SynthesisPipeline.<>c__DisplayClass12_02.<<AddPatch>b__0>d.MoveNext() in D:\a\Synthesis\Synthesis\Mutagen.Bethesda.Synthesis\SynthesisPipeline.cs:line 99
--- End of stack trace from previous location ---
   at Mutagen.Bethesda.Synthesis.SynthesisPipeline.Run(RunSynthesisMutagenPatcher args, Nullable1 exportKey, IFileSystem fileSystem) in D:\a\Synthesis\Synthesis\Mutagen.Bethesda.Synthesis\SynthesisPipeline.cs:line 559
   at Mutagen.Bethesda.Synthesis.SynthesisPipeline.Run(RunSynthesisMutagenPatcher args, IFileSystem fileSystem) in D:\a\Synthesis\Synthesis\Mutagen.Bethesda.Synthesis\SynthesisPipeline.cs:line 456
   at Mutagen.Bethesda.Synthesis.SynthesisPipeline.<>c__DisplayClass36_0.<<InternalRun>b__1>d.MoveNext() in D:\a\Synthesis\Synthesis\Mutagen.Bethesda.Synthesis\SynthesisPipeline.cs:line 419
`

**Comment by klimurk** [comment]
Yeah, just need to set inputs/outputs + disable logging  -___-

**Comment by SteveTownsend** [comment]
I am glad you sorted it out. Sorry I spaced on it last night, I am in the
middle of some major LO resuscitation and surgery and got carried away with
SkyTEST Redux CR

**Comment by SteveTownsend** [comment]
PS a lot of people have moved over to Immersive Equipment Displays, it's
way more efficient, and more manageable if you use presets people have
published. There's a separate Synthesis patcher for that, to fix up some of
the displayed models.
